name: Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Generate TypeDoc documentation
        run: npm run docs

      - name: Commit generated docs
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add docs/
          git commit -m "Update documentation"
          git push origin HEAD:docs

